name: Linkrot
on:
  schedule:
    - cron: '0 13 * * MON'
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fix links
        uses: tmcw/notfoundbot@v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
